### PR TITLE
* add file extension

### PR DESCRIPTION
**Pull request by Ethella**
### 📦 Pull Request

Fix incompatible issue with Nuxt

https://github.com/ethereum/js-ethereum-cryptography/issues/14

```
Cannot find module 
'/var/www/slurpeevibe-stage.modeng.dev/private/git/.output/server/node_modules/ethereum-cryptography/keccak' 
imported from /var/www/slurpeevibe-stage.modeng.dev/private/git/.output/server/chunks/index.post.mjs
\nDid you mean to import ethereum-cryptography/keccak.js?
```

### CODE REVIEW

**Review by justinnout — COMMENTED** [review]
Is this import change going to break things for existing clients?

**Comment by Ethella** [comment]
>Is this import change going to break things for existing clients?
Great call, I'm actually testing it

**Comment by Ethella** [comment]
image
Compiled successfully

**Review by justinnout — APPROVED** [review]

**Comment by magiclabsFE** [comment]
:rocket: PR was released in [`v1.10.1`](https://github.com/magiclabs/magic-admin-js/releases/tag/v1.10.1) :rocket:

**Pull request merged**
